<?php

/**
 * @OA\Schema(
 *     schema="VehicleUpdateRequestSchema",
 *     description="Vehicle update request Schema",
 *     @OA\Property(
 *         property="origin",
 *         type="string",
 *         example="SK"
 *     ),
 *     @OA\Property(
 *         property="brand",
 *         type="string",
 *         example="Peugeot"
 *     ),
 *     @OA\Property(
 *         property="model",
 *         type="string",
 *         example="Clio"
 *     ),
 *     @OA\Property(
 *         property="version",
 *         type="string",
 *         example="ADVANTAGE"
 *     ),
 *     @OA\Property(
 *         property="version_description",
 *         type="string",
 *         example="ADVANTAGE Description"
 *     ),
 *     @OA\Property(
 *         property="fuel_type",
 *         type="string",
 *         description="One of:Gasoline,Diesel,Hybrid,Electric,LPG,Other Fuels,Alcohol,Cryogenic,Waterstof",
 *         example="Diesel"
 *     ),
 *     @OA\Property(
 *         property="gearbox",
 *         type="integer",
 *         description="1-automatic, 0-manual",
 *         example="1"
 *     ),
 *     @OA\Property(
 *         property="km",
 *         type="string",
 *         example="1234"
 *     ),
 *     @OA\Property(
 *         property="cm3",
 *         type="integer",
 *         example="1234"
 *     ),
 *     @OA\Property(
 *         property="kw",
 *         type="integer",
 *         example="1234"
 *     ),
 *     @OA\Property(
 *         property="hp",
 *         type="integer",
 *         example="1234"
 *     ),
 *     @OA\Property(
 *         property="firstregistration",
 *         type="string",
 *         example="01/01/2018"
 *     ),
 *     @OA\Property(
 *         property="interior",
 *         type="string",
 *         example="1DL"
 *     ),
 *     @OA\Property(
 *         property="color_code",
 *         type="string",
 *         example="23D2"
 *     ),
 *     @OA\Property(
 *         property="color_description",
 *         type="string",
 *         example="Ultimate Rot (3-Schicht-Lackierung)"
 *     ),
 *     @OA\Property(
 *         property="options_code",
 *         type="string",
 *         example="45G3"
 *     ),
 *     @OA\Property(
 *         property="option_code_description",
 *         type="string",
 *         example="Satinweiß Metallic · Navigation: SD-Navigationssystem mit NNG Technologie · Lackierung: Metallic Lenkrad"
 *     ),
 *     @OA\Property(
 *         property="co2",
 *         type="integer",
 *         example="1111"
 *     ),
 *     @OA\Property(
 *         property="b2b_price_ex_vat",
 *         type="string",
 *         example="19571.43"
 *     ),
 *     @OA\Property(
 *         property="vat_deductible",
 *         type="string",
 *         example="1"
 *     ),
 *     @OA\Property(
 *         property="damages_excl_vat_info",
 *         type="string",
 *         example="MAX 250 €"
 *     ),
 *     @OA\Property(
 *         property="disponsibility",
 *         type="string",
 *         example="10/27/2017"
 *     ),
 *     @OA\Property(
 *         property="loading_place",
 *         type="string",
 *         example="2455 - Ungeheuer Niederlassung Bruchsal"
 *     ),
 *     @OA\Property(
 *         property="note",
 *         type="string",
 *         example="Note"
 *     ),
 *     @OA\Property(
 *         property="language_option_code_description",
 *         type="integer",
 *         description="1-English, 0-Anything else",
 *         example="1"
 *     ),
 *     @OA\Property(
 *         property="currency_iso_codification",
 *         type="string",
 *         example="EUR"
 *     ),
 *     @OA\Property(
 *         property="url_address",
 *         type="string",
 *         example="www.someurl.com"
 *     ),
 *     @OA\Property(
 *         property="media_path",
 *         type="string",
 *         example="www.somesite.com/26321257-1.JPG;26321257-2.JPG;26321257-3.JPG;"
 *     ),
 *     @OA\Property(
 *         property="condition_type",
 *         type="string",
 *         description="One of:used,new,demo,new_registered",
 *         example="used"
 *     ),
 *     @OA\Property(
 *         property="vehicle_type",
 *         type="string",
 *         description="One of:LCV,Passenger,Truck",
 *         example="Passenger"
 *     ),
 *     @OA\Property(
 *         property="account_id",
 *         type="integer",
 *         example="2"
 *     ),
 *     @OA\Property(
 *         property="body_type",
 *         type="string",
 *         example="limousine"
 *     ),
 *     @OA\Property(
 *         property="sku_number",
 *         type="string",
 *         example="10148225-AWD / 22299272"
 *     ),
 *     @OA\Property(
 *         property="certification_code",
 *         type="string",
 *         example="5F31"
 *     ),
 *     @OA\Property(
 *         property="fuel_consumption_city",
 *         type="string",
 *         example="6.7"
 *     ),
 *     @OA\Property(
 *         property="fuel_consumption_land",
 *         type="string",
 *         example="7"
 *     ),
 *     @OA\Property(
 *         property="fuel_consumption_rating",
 *         type="string",
 *         example="Good and economic"
 *     ),
 *     @OA\Property(
 *         property="fuel_consumption_total",
 *         type="string",
 *         example="7.4"
 *     ),
 *     @OA\Property(
 *         property="cylinders",
 *         type="integer",
 *         example="4"
 *     ),
 *     @OA\Property(
 *         property="documents",
 *         type="string",
 *         example="Document.txt"
 *     ),
 *     @OA\Property(
 *         property="coc",
 *         type="string",
 *         example="/path/to/CocDocument.txt"
 *     ),
 *     @OA\Property(
 *         property="doors",
 *         type="integer",
 *         example="4"
 *     ),
 *     @OA\Property(
 *         property="drive_type",
 *         type="string",
 *         example="Front-wheel"
 *     ),
 *     @OA\Property(
 *         property="has_warranty",
 *         type="integer",
 *         example="1"
 *     ),
 *     @OA\Property(
 *         property="id",
 *         type="string",
 *         example="Autoscout => 23"
 *     ),
 *     @OA\Property(
 *         property="model_group",
 *         type="string",
 *         example="A-CLASS"
 *     ),
 *     @OA\Property(
 *         property="pollution_norm",
 *         type="string",
 *         description="One of:EURO0,EURO1,EURO2,EURO3,EURO4,EURO5,EURO6,EURO5A,EURO5B,EURO6A,EURO6B,EURO6C,EURO6D,EURO6+",
 *         example="EURO5"
 *     ),
 *     @OA\Property(
 *         property="price",
 *         type="number",
 *         example="40252.00"
 *     ),
 *     @OA\Property(
 *         property="price_history",
 *         type="number",
 *         example="40223, 40211, 50255 "
 *     ),
 *     @OA\Property(
 *         property="price_new",
 *         type="number",
 *         example="50255.00"
 *     ),
 *     @OA\Property(
 *         property="properties",
 *         type="string",
 *         example="prop1, prop2, prop3"
 *     ),
 *     @OA\Property(
 *         property="additional_properties",
 *         type="string",
 *         example="prop1, prop2, prop3"
 *     ),
 *     @OA\Property(
 *         property="seats",
 *         type="integer",
 *         example="4"
 *     ),
 *     @OA\Property(
 *         property="segmentation_id",
 *         type="string",
 *         example="45"
 *     ),
 *     @OA\Property(
 *         property="teaser",
 *         type="string",
 *         example="car_euro"
 *     ),
 *     @OA\Property(
 *         property="videos",
 *         type="string",
 *         example="27930017-1.AVI;27930017-2.AVI;27930017-3.MOV;"
 *     ),
 *     @OA\Property(
 *         property="weight",
 *         type="integer",
 *         example="3234"
 *     ),
 *     required={"origin", "brand", "model", "version", "version_description", "fuel_type", "gearbox", "km", "cm3", "kw", "hp", "firstregistration", "color_description", "co2", "b2b_price_ex_vat", "vat_deductible", "loading_place", "language_option_code_description", "currency_iso_codification", "condition_type", "vehicle_type", "pollution_norm", "weight"}
 * )
 *
 */


/**
 * @OA\Schema(
 *     schema="VehicleStoreRequestSchema",
 *     description="Vehicle store request Schema",
 *     @OA\Property(
 *         property="manufacturer_id",
 *         description="VIN, an, caf, ident or any other unique identifier of the vehicle",
 *         type="string",
 *         example="W0VF86E04K4146868"
 *     ),
 *     @OA\Property(
 *         property="origin",
 *         type="string",
 *         example="SK"
 *     ),
 *     @OA\Property(
 *         property="brand",
 *         type="string",
 *         example="Peugeot"
 *     ),
 *     @OA\Property(
 *         property="model",
 *         type="string",
 *         example="Clio"
 *     ),
 *     @OA\Property(
 *         property="version",
 *         type="string",
 *         example="ADVANTAGE"
 *     ),
 *     @OA\Property(
 *         property="version_description",
 *         type="string",
 *         example="ADVANTAGE Description"
 *     ),
 *     @OA\Property(
 *         property="fuel_type",
 *         type="string",
 *         description="One of:Gasoline,Diesel,Hybrid,Electric,LPG,Other Fuels,Alcohol,Cryogenic,Waterstof",
 *         example="Diesel"
 *     ),
 *     @OA\Property(
 *         property="gearbox",
 *         type="integer",
 *         description="1-automatic, 0-manual",
 *         example="1"
 *     ),
 *     @OA\Property(
 *         property="km",
 *         type="integer",
 *         example="1234"
 *     ),
 *     @OA\Property(
 *         property="cm3",
 *         type="integer",
 *         example="1234"
 *     ),
 *     @OA\Property(
 *         property="kw",
 *         type="integer",
 *         example="1234"
 *     ),
 *     @OA\Property(
 *         property="hp",
 *         type="integer",
 *         example="1234"
 *     ),
 *     @OA\Property(
 *         property="firstregistration",
 *         type="string",
 *         example="01/01/2018"
 *     ),
 *     @OA\Property(
 *         property="interior",
 *         type="string",
 *         example="1DL"
 *     ),
 *     @OA\Property(
 *         property="color_code",
 *         type="string",
 *         example="23D2"
 *     ),
 *     @OA\Property(
 *         property="color_description",
 *         type="string",
 *         example="Ultimate Rot (3-Schicht-Lackierung)"
 *     ),
 *     @OA\Property(
 *         property="options_code",
 *         type="string",
 *         example="45G3"
 *     ),
 *     @OA\Property(
 *         property="option_code_description",
 *         type="string",
 *         example="Satinweiß Metallic · Navigation: SD-Navigationssystem mit NNG Technologie · Lackierung: Metallic Lenkrad"
 *     ),
 *     @OA\Property(
 *         property="co2",
 *         type="integer",
 *         example="1111"
 *     ),
 *     @OA\Property(
 *         property="b2b_price_ex_vat",
 *         type="string",
 *         example="19571.43"
 *     ),
 *     @OA\Property(
 *         property="vat_deductible",
 *         type="string",
 *         example="1"
 *     ),
 *     @OA\Property(
 *         property="damages_excl_vat_info",
 *         type="string",
 *         example="MAX 250 €"
 *     ),
 *     @OA\Property(
 *         property="disponsibility",
 *         type="string",
 *         example="10/27/2017"
 *     ),
 *     @OA\Property(
 *         property="loading_place",
 *         type="string",
 *         example="2455 - Ungeheuer Niederlassung Bruchsal"
 *     ),
 *     @OA\Property(
 *         property="note",
 *         type="string",
 *         example="Note"
 *     ),
 *     @OA\Property(
 *         property="language_option_code_description",
 *         type="integer",
 *         description="1-English, 0-Anything else",
 *         example="1"
 *     ),
 *     @OA\Property(
 *         property="currency_iso_codification",
 *         type="string",
 *         example="EUR"
 *     ),
 *     @OA\Property(
 *         property="url_address",
 *         type="string",
 *         example="www.someurl.com"
 *     ),
 *     @OA\Property(
 *         property="media_path",
 *         type="string",
 *         example="www.somesite.com/26321257-1.JPG;26321257-2.JPG;26321257-3.JPG;"
 *     ),
 *     @OA\Property(
 *         property="condition_type",
 *         type="string",
 *         description="One of:used,new,demo,new_registered",
 *         example="used"
 *     ),
 *     @OA\Property(
 *         property="vehicle_type",
 *         type="string",
 *         description="One of:LCV,Passenger,Truck",
 *         example="Passenger"
 *     ),
 *     @OA\Property(
 *         property="account_id",
 *         type="string",
 *         example="2"
 *     ),
 *     @OA\Property(
 *         property="body_type",
 *         type="string",
 *         example="limousine"
 *     ),
 *     @OA\Property(
 *         property="sku_number",
 *         type="string",
 *         example="10148225-AWD / 22299272"
 *     ),
 *     @OA\Property(
 *         property="certification_code",
 *         type="string",
 *         example="5F31"
 *     ),
 *     @OA\Property(
 *         property="fuel_consumption_city",
 *         type="string",
 *         example="6.7"
 *     ),
 *     @OA\Property(
 *         property="fuel_consumption_land",
 *         type="string",
 *         example="7"
 *     ),
 *     @OA\Property(
 *         property="fuel_consumption_rating",
 *         type="string",
 *         example="Good and economic"
 *     ),
 *     @OA\Property(
 *         property="fuel_consumption_total",
 *         type="string",
 *         example="7.4"
 *     ),
 *     @OA\Property(
 *         property="cylinders",
 *         type="integer",
 *         example="4"
 *     ),
 *     @OA\Property(
 *         property="documents",
 *         type="string",
 *         example="Document.txt"
 *     ),
 *     @OA\Property(
 *         property="coc",
 *         type="string",
 *         example="/path/to/CocDocument.txt"
 *     ),
 *     @OA\Property(
 *         property="doors",
 *         type="integer",
 *         example="4"
 *     ),
 *     @OA\Property(
 *         property="drive_type",
 *         type="string",
 *         example="Front-wheel"
 *     ),
 *     @OA\Property(
 *         property="has_warranty",
 *         type="integer",
 *         example="1"
 *     ),
 *     @OA\Property(
 *         property="id",
 *         type="string",
 *         example="Autoscout => 23"
 *     ),
 *     @OA\Property(
 *         property="model_group",
 *         type="string",
 *         example="A-CLASS"
 *     ),
 *     @OA\Property(
 *         property="pollution_norm",
 *         type="string",
 *         description="One of:EURO0,EURO1,EURO2,EURO3,EURO4,EURO5,EURO6,EURO5A,EURO5B,EURO6A,EURO6B,EURO6C,EURO6D,EURO6+",
 *         example="EURO5"
 *     ),
 *     @OA\Property(
 *         property="price",
 *         type="number",
 *         example="40252.00"
 *     ),
 *     @OA\Property(
 *         property="price_history",
 *         type="number",
 *         example="40223, 40211, 50255 "
 *     ),
 *     @OA\Property(
 *         property="price_new",
 *         type="number",
 *         example="50255.00"
 *     ),
 *     @OA\Property(
 *         property="properties",
 *         type="string",
 *         example="prop1, prop2, prop3"
 *     ),
 *     @OA\Property(
 *         property="additional_properties",
 *         type="string",
 *         example="prop1, prop2, prop3"
 *     ),
 *     @OA\Property(
 *         property="seats",
 *         type="integer",
 *         example="4"
 *     ),
 *     @OA\Property(
 *         property="segmentation_id",
 *         type="string",
 *         example="45"
 *     ),
 *     @OA\Property(
 *         property="teaser",
 *         type="string",
 *         example="car_euro"
 *     ),
 *     @OA\Property(
 *         property="videos",
 *         type="string",
 *         example="27930017-1.AVI;27930017-2.AVI;27930017-3.MOV;"
 *     ),
 *     @OA\Property(
 *         property="weight",
 *         type="integer",
 *         example="3234"
 *     ),
 *     required={"manufacturer_id", "origin", "brand", "model", "version", "version_description", "fuel_type", "gearbox", "km", "cm3", "kw", "hp", "firstregistration", "color_description", "co2", "b2b_price_ex_vat", "vat_deductible", "loading_place", "language_option_code_description", "currency_iso_codification", "condition_type", "vehicle_type", "pollution_norm", "weight"}
 * )
 *
 */


/**
 * @OA\Schema(
 *     schema="VehicleResponseSchema",
 *     description="Vehicle response Schema",
 *     @OA\Property(
 *         property="id",
 *         type="integer",
 *         example=16565
 *     ),
 *     @OA\Property(
 *         property="manufacturer_id",
 *         type="string",
 *         example="WAUZZZF47KA027542"
 *     ),
 *     @OA\Property(
 *         property="origin",
 *         type="string",
 *         example="NL"
 *     ),
 *     @OA\Property(
 *         property="brand",
 *         type="string",
 *         example="NL"
 *     ),
 *     @OA\Property(
 *         property="model",
 *         type="string",
 *         example="AUDI"
 *     ),
 *     @OA\Property(
 *         property="version",
 *         type="string",
 *         example="AVANT 40 TFSI 190PK S-TRONIC S LINE EDITION"
 *     ),
 *     @OA\Property(
 *         property="version_description",
 *         type="string",
 *         example="AVANT 40 TFSI 190PK S-TRONIC S LINE EDITION DESCRIPTION"
 *     ),
 *     @OA\Property(
 *         property="fuel_type",
 *         type="string",
 *         example="Gasoline"
 *     ),
 *     @OA\Property(
 *         property="gearbox",
 *         type="string",
 *         example="A"
 *     ),
 *     @OA\Property(
 *         property="km",
 *         type="integer",
 *         example=49555
 *     ),
 *     @OA\Property(
 *         property="firstregistration",
 *         type="string",
 *         example="2019-01-21T23:00:00.000000Z",
 *     ),
 *     @OA\Property(
 *         property="interior",
 *         type="string",
 *         example="Antraciet",
 *     ),
 *     @OA\Property(
 *         property="color_code",
 *         type="string",
 *         example="2FB",
 *     ),
 *     @OA\Property(
 *         property="color_description",
 *         type="string",
 *         example="Floretsilver(zilver)",
 *     ),
 *     @OA\Property(
 *         property="options_code",
 *         type="string",
 *         example="0F",
 *     ),
 *     @OA\Property(
 *         property="option_code_description",
 *         type="string",
 *         example="Sports seats Anti-lock braking system Cruise control Driver's airbag Front central armrest Front side airbags Height adjustable steering wheel Onboard computer Passenger airbag Rear parking sensor Remote central locking Roof rails Roof spoiler Sports suspensio"
 *     ),
 *     @OA\Property(
 *         property="option_code_description_english",
 *         type="string",
 *         example="Sports seats Anti-lock braking system Cruise control Driver's airbag Front central armrest Front side airbags Height adjustable steering wheel Onboard computer Passenger airbag Rear parking sensor Remote central locking Roof rails Roof spoiler Sports suspensio"
 *     ),
 *     @OA\Property(
 *         property="b2b_price_ex_vat",
 *         type="string",
 *         example="35900.00"
 *     ),
 *     @OA\Property(
 *         property="price_in_euro",
 *         type="string",
 *         example="35900.00"
 *     ),
 *     @OA\Property(
 *         property="vat_deductible",
 *         type="string",
 *         example="1"
 *     ),
 *     @OA\Property(
 *         property="damages_excl_vat_info",
 *         type="string",
 *         example="n"
 *     ),
 *     @OA\Property(
 *         property="disponibility",
 *         type="string",
 *         example="2021-07-23"
 *     ),
 *     @OA\Property(
 *         property="language_option_code_description",
 *         type="string",
 *         example="1"
 *     ),
 *     @OA\Property(
 *         property="currency_iso_codification",
 *         type="string",
 *         example="EUR"
 *     ),
 *     @OA\Property(
 *         property="url_address",
 *         type="string",
 *         example="https://www.pouw.nl/stock/stocks/detail/28073458"
 *     ),
 *     @OA\Property(
 *         property="note",
 *         type="string",
 *         example="Deze Audi A4 hebben wij professioneel en volgens strenge dealereisen rijklaar gemaakt. Hij staat klaar voor vertrek dus je kunt snel met hem op weg. Zo hebben wij de auto op 130 punten technisch gecheckt en heeft de auto de komende 10.000 kilometer of binnen 6 maanden een onderhoudsbeurt nodig? Dan hebben wij deze alvast uitgevoerd. Ook is de binnen- en buitenkant uitgebreid gereinigd en heeft de auto een volle tank brandstof.  Bovendien voorzien wij je Audi van 6 maanden Audi Selectie :plus-garantie inclusief pechhulp binnen heel Europa. <br /><br />Pouw is jouw bekende gezicht voor Audi, Volkswagen, SEAT, &Scaron;KODA en Volkswagen Bedrijfswagens. We zijn er voor je met de verkoop van nieuwe en gebruikte personen- en bedrijfswagens en met onze werkplaatsen, financierings- en verhuuractiviteiten en ons schadeherstelbedrijf. Verwacht van ons snelheid, zekerheid en duidelijkheid in onze manier van doen. Dat past bij onze merken, dat past bij onze collega&rsquo;s, dat past bij onze regio en het past bij jou. Zo gaan we samen vooruit. <br /><br />Wij nodigen je graag uit om deze Audi te komen bekijken en ervaren met een proefrit. Wanneer kom je eens langs?"
 *     ),
 *     @OA\Property(
 *         property="media_path",
 *         type="array",
 *         @OA\Items(
 *         ),
 *         example={"http://carmarket/de_images/101658196_01.jpg", "http://carmarket/de_images/101658196_02.jpg"}
 *     ),
 *     @OA\Property(
 *         property="connectivity_partner_id",
 *         type="string",
 *         example="31300"
 *     ),
 *     @OA\Property(
 *         property="body_type",
 *         type="string",
 *         example="SUV"
 *     ),
 *     @OA\Property(
 *         property="sku_number",
 *         type="string",
 *         example="15621633-AWD"
 *     ),
 *     @OA\Property(
 *         property="certification_code",
 *         type="string",
 *         example="2FD"
 *     ),
 *     @OA\Property(
 *         property="condition_type",
 *         type="string",
 *         example="used"
 *     ),
 *     @OA\Property(
 *         property="fuel_consumption_city",
 *         type="string",
 *         example="5.8"
 *     ),
 *     @OA\Property(
 *         property="fuel_consumption_land",
 *         type="string",
 *         example="5.8"
 *     ),
 *     @OA\Property(
 *         property="fuel_consumption_rating",
 *         type="string",
 *         example="C"
 *     ),
 *     @OA\Property(
 *         property="fuel_consumption_total",
 *         type="number",
 *         example="5.8"
 *     ),
 *     @OA\Property(
 *         property="cylinders",
 *         type="integer",
 *         example="4"
 *     ),
 *     @OA\Property(
 *         property="documents",
 *         type="string",
 *         example="www.url.com/doc1;www.url.com/doc2;"
 *     ),
 *     @OA\Property(
 *         property="doors",
 *         type="integer",
 *         example="5"
 *     ),
 *     @OA\Property(
 *         property="drive_type",
 *         type="string",
 *         example="motorisch"
 *     ),
 *     @OA\Property(
 *         property="has_warranty",
 *         type="boolean",
 *         example="true"
 *     ),
 *     @OA\Property(
 *         property="external_id",
 *         @OA\Property(
 *             property="DE",
 *             type="string",
 *             example="45646"
 *         )
 *     ),
 *     @OA\Property(
 *         property="model_group",
 *         type="string",
 *         example="A4 Avant",
 *     ),
 *     @OA\Property(
 *         property="pollution_norm",
 *         type="string",
 *         example="EURO1",
 *     ),
 *     @OA\Property(
 *         property="price",
 *         type="string",
 *         example="35900.00"
 *     ),
 *     @OA\Property(
 *         property="price_history",
 *         type="string",
 *         example="35900.00, 45900.00, 55900.00"
 *     ),
 *     @OA\Property(
 *         property="price_new",
 *         type="number",
 *         example="35900.00"
 *     ),
 *     @OA\Property(
 *         property="properties",
 *         type="array",
 *         @OA\Items(
 *         ),
 *         example={"prop1", "prop2"}
 *     ),
 *     @OA\Property(
 *         property="additional_properties",
 *         type="array",
 *         @OA\Items(
 *         ),
 *         example={"prop1", "prop2"}
 *     ),
 *     @OA\Property(
 *         property="seats",
 *         type="integer",
 *         example="5"
 *     ),
 *     @OA\Property(
 *         property="segmentation_id",
 *         type="string",
 *         example="FD5445FDF"
 *     ),
 *     @OA\Property(
 *         property="seller",
 *         type="string",
 *         example="Pouw Deventer, Deventer, NL"
 *     ),
 *     @OA\Property(
 *         property="teaser",
 *         type="string",
 *         example="34FD34"
 *     ),
 *     @OA\Property(
 *         property="type_name",
 *         type="string",
 *         example="Audi, A4, Avant 40 TFSI 190pk S-Tronic S Line Edition"
 *     ),
 *     @OA\Property(
 *         property="videos",
 *         type="string",
 *         example="www.url.com/video1;www.url.com/video2;"
 *     ),
 *     @OA\Property(
 *         property="weight",
 *         type="integer",
 *         example="2500"
 *     ),
 *     @OA\Property(
 *         property="vehicle_type",
 *         type="string",
 *         example="Passenger"
 *     ),
 *     @OA\Property(
 *         property="country",
 *         type="string",
 *         example="nl"
 *     ),
 *     @OA\Property(
 *         property="company",
 *         type="string",
 *         example="Pouw Deventer"
 *     ),
 *     @OA\Property(
 *         property="company_id",
 *         type="integer",
 *         example="86"
 *     ),
 *     @OA\Property(
 *         property="created_at",
 *         type="date",
 *         example="2021-12-08T15:14:02.000000Z"
 *     ),
 *     @OA\Property(
 *         property="updated_at",
 *         type="date",
 *         example="2021-12-08T15:14:02.000000Z"
 *     ),
 *     @OA\Property(
 *         property="coc",
 *         type="string",
 *         example="www.path.com/coc"
 *     ),
 *     @OA\Property(
 *         property="co2",
 *         type="integer",
 *         example=152
 *     ),
 *     @OA\Property(
 *         property="cm3",
 *         type="integer",
 *         example=1984
 *     ),
 *     @OA\Property(
 *         property="kw",
 *         type="integer",
 *         example=140
 *     ),
 *     @OA\Property(
 *         property="hp",
 *         type="integer",
 *         example=150
 *     )
 * )
 *
 */



